const {test,after}=require('node:test');const assert=require('node:assert/strict');const account=require('../api/account.js'),progress=require('../api/progress.js');const A=require('../lib/account.cjs');
const originalFetch=global.fetch;after(()=>{global.fetch=originalFetch});
const uid='11111111-1111-4111-8111-111111111111';
const user={id:uid,email:'test@example.invalid'};const session={access_token:'fake-access',refresh_token:'fake-refresh',expires_in:3600,user};
function configured(){process.env.SUPABASE_URL='https://test-project.supabase.co';process.env.SUPABASE_ANON_KEY='test-key';process.env.APP_ORIGIN='https://randomfortune-game.vercel.app'}
async function call(handler,body,headers={},method='POST'){const req={method,headers:{origin:'https://randomfortune-game.vercel.app','content-type':'application/json','x-forge-request':'1',...headers},body};const res={headers:{},statusCode:200,setHeader(k,v){this.headers[k]=v},status(s){this.statusCode=s;return this},json(v){this.data=v;return this}};await handler(req,res);return res}
function mock(routes){const requests=[];global.fetch=async(url,opt)=>{requests.push({url,opt});const match=routes.find(r=>url.includes(r.path));assert.ok(match,url);return{ok:!match.status||match.status<400,status:match.status||200,json:async()=>match.data}};return requests}
test('unconfigured service honestly disables signup and preserves guest mode',async()=>{process.env.SUPABASE_URL='https://different-project.supabase.co';delete process.env.SUPABASE_ANON_KEY;delete process.env.SUPABASE_PUBLISHABLE_KEY;let r=await call(account,{action:'status'});assert.deepEqual(r.data,{configured:false,user:null});r=await call(account,{action:'signup',email:user.email,password:'mock-password-only'});assert.equal(r.statusCode,503);assert.equal(r.data.error,'NOT_CONFIGURED')});
test('cross-origin, missing custom header, wrong method are rejected before auth',async()=>{configured();let calls=0;global.fetch=async()=>{calls++;throw Error()};assert.equal((await call(account,{action:'signin'},{origin:'https://attacker.invalid'})).statusCode,403);assert.equal((await call(account,{action:'signin'},{'x-forge-request':''})).statusCode,403);assert.equal((await call(account,{action:'status'},{},'GET')).statusCode,405);assert.equal(calls,0)});
test('signup requiring confirmation does not create fake session',async()=>{configured();mock([{path:'/signup',data:{user}}]);const r=await call(account,{action:'signup',email:user.email,password:'mock-password-only'});assert.deepEqual(r.data,{confirmationRequired:true});assert.equal(r.headers['Set-Cookie'],undefined)});
test('login tokens stay in HttpOnly secure cookies, never JSON response',async()=>{configured();mock([{path:'/token',data:session}]);const r=await call(account,{action:'signin',email:user.email,password:'mock-password-only'});assert.equal(r.statusCode,200);assert.deepEqual(r.data,{user});for(const cookie of r.headers['Set-Cookie']){assert.match(cookie,/^__Host-/);assert.match(cookie,/HttpOnly; Secure; SameSite=Lax/)}assert.equal(JSON.stringify(r.data).includes('fake-access'),false);assert.equal(r.headers['Cache-Control'],'no-store, private')});
test('bad password and rate limits return safe errors without upstream details',async()=>{configured();mock([{path:'/token',status:400,data:{error_code:'invalid_credentials',msg:'sensitive internal message'}}]);let r=await call(account,{action:'signin',email:user.email,password:'mock-password-only'});assert.equal(r.statusCode,401);assert.ok(!JSON.stringify(r.data).includes('sensitive'));mock([{path:'/token',status:429,data:{}}]);r=await call(account,{action:'signin',email:user.email,password:'mock-password-only'});assert.equal(r.statusCode,429)});
test('session refresh verifies user before exposing identity',async()=>{configured();const reqs=mock([{path:'/token',data:session},{path:'/user',data:user}]);const r=await call(account,{action:'status'},{cookie:'__Host-ff-refresh=fake-refresh'});assert.deepEqual(r.data.user,user);assert.equal(reqs.length,2);assert.ok(r.headers['Set-Cookie'])});
test('verification and recovery tokens have distinct types; reset revokes sessions',async()=>{configured();let reqs=mock([{path:'/verify',data:session}]);let r=await call(account,{action:'verify',email:user.email,code:'123456'});assert.equal(r.statusCode,200);assert.equal(JSON.parse(reqs[0].opt.body).type,'signup');reqs=mock([{path:'/verify',data:session},{path:'/user',data:user},{path:'/logout',data:null}]);r=await call(account,{action:'reset',email:user.email,code:'123456',password:'mock-new-password'});assert.equal(r.statusCode,200);assert.equal(JSON.parse(reqs[0].opt.body).type,'recovery');assert.ok(reqs.at(-1).url.includes('scope=global'));assert.ok(r.headers['Set-Cookie'].every(c=>c.includes('Max-Age=0')))});
test('logout revokes current session and expires both cookies',async()=>{configured();const reqs=mock([{path:'/user',data:user},{path:'/logout',data:null}]);const r=await call(account,{action:'logout'},{cookie:'__Host-ff-access=fake-access'});assert.equal(r.data.ok,true);assert.ok(reqs.at(-1).url.includes('scope=local'));assert.ok(r.headers['Set-Cookie'].every(c=>c.includes('Max-Age=0')))});
test('anonymous and mismatched-owner saves cannot reach storage',async()=>{configured();let reqs=mock([{path:'/user',data:user}]);let r=await call(progress,{action:'save',owner:uid,data:{levels:{},essence:120},revision:null});assert.equal(r.statusCode,401);r=await call(progress,{action:'save',owner:'other-user',data:{levels:{},essence:120},revision:null},{cookie:'__Host-ff-access=fake-access'});assert.equal(r.statusCode,409);assert.equal(reqs.length,1)});
test('stale revision returns conflict and preserves remote data',async()=>{configured();const reqs=mock([{path:'/user',data:user},{path:'/rpc/',data:[]}]);const r=await call(progress,{action:'save',owner:uid,data:{levels:{'0:1':5},essence:0},revision:2},{cookie:'__Host-ff-access=fake-access'});assert.equal(r.statusCode,409);const sent=JSON.parse(reqs.at(-1).opt.body);assert.equal(sent.expected_revision,2);assert.equal(sent.user_id,undefined)});
test('valid cloud save returns new revision; invalid currency and unknown units rejected',async()=>{configured();mock([{path:'/user',data:user},{path:'/rpc/',data:[{data:{levels:{'0:1':2},essence:108},revision:3}]}]);const r=await call(progress,{action:'save',owner:uid,data:{levels:{'0:1':2},essence:108},revision:2},{cookie:'__Host-ff-access=fake-access'});assert.equal(r.data.record.revision,3);for(const p of [{levels:{},essence:-1},{levels:{'2:1':4},essence:0},{levels:{'0:1':31},essence:0},{levels:[],essence:0}])assert.throws(()=>A.progress(p));assert.throws(()=>A.input({body:'{broken'}))});
test('cloud validation accepts level30 tier6 and ranks1-10 but rejects locked or malformed skills',()=>{assert.equal(A.progress({levels:{'9:6':30},skills:{'9:6:5':10},essence:5}).skills['9:6:5'],10);for(const skills of [{'9:6:5':11},{'9:6:6':1},{'9:6:5':0},{'9:1:1':2},[]])assert.throws(()=>A.progress({levels:{'9:6':30},skills,essence:5}));assert.throws(()=>A.progress({levels:{'9:6':29},skills:{'9:6:5':1},essence:5}))});

test('elemental v4 progress validates final branch unlocks and rejects removed tiers',()=>{
 const {progress}=require('../lib/account.cjs');
 assert.equal(progress({version:4,levels:{'3:5':20},skills:{'3:5:6':2},essence:10}).skills['3:5:6'],2);
 assert.equal(progress({version:4,levels:{},skills:{'8:1:0':2},essence:0}).skills['8:1:0'],2);
 for(const value of [
  {levels:{'8:6':30},skills:{}},
  {levels:{'3:2':2},skills:{}},
  {levels:{'8:5':9},skills:{'8:5:5':2}},
  {levels:{'8:5':19},skills:{'8:5:6':2}},
  {levels:{'8:1':30},skills:{'8:1:1':2}},
 ])assert.throws(()=>progress({version:4,essence:0,...value}));
});

test('deployment public config activates auth without environment secrets; custom projects require their own key',async()=>{delete process.env.SUPABASE_URL;delete process.env.SUPABASE_ANON_KEY;delete process.env.SUPABASE_PUBLISHABLE_KEY;assert.match(A.config().key,/^sb_publishable_/);assert.equal((await call(account,{action:'status'})).data.configured,true);process.env.SUPABASE_URL='https://another.supabase.co';assert.equal(A.config(),null);process.env.SUPABASE_PUBLISHABLE_KEY='sb_publishable_override';assert.equal(A.config().key,'sb_publishable_override');delete process.env.SUPABASE_PUBLISHABLE_KEY;configured()});

test('guardian progress preserves valid permanent data and rejects invalid nickname or experience',()=>{const base={version:4,levels:{},skills:{},essence:0};assert.deepEqual(A.progress({...base,guardian:{nickname:'별이',xp:49500}}).guardian,{nickname:'별이',xp:49500});for(const guardian of [{nickname:'',xp:0},{nickname:'<script>',xp:0},{nickname:'별이',xp:-1},{nickname:'별이',xp:49501},{nickname:'별이',xp:1.5}])assert.throws(()=>A.progress({...base,guardian}))});

test('guardian endpoint rejects anonymous and mismatched-owner access before RPC',async()=>{configured();const guardian=require('../api/guardian.js');const reqs=mock([{path:'/user',data:user}]);assert.equal((await call(guardian,{action:'load',owner:uid})).statusCode,401);assert.equal((await call(guardian,{action:'load',owner:'other'},{cookie:'__Host-ff-access=fake-access'})).statusCode,409);assert.equal(reqs.length,1)});
test('guardian endpoint normalizes nickname, isolates payload from currencies and validates XP/name',async()=>{configured();const guardian=require('../api/guardian.js');const reqs=mock([{path:'/user',data:user},{path:'/rpc/forge_guardian',data:{owner:uid,guardian:{nickname:'별이',xp:20}}}]);const r=await call(guardian,{action:'save',owner:uid,payload:{nickname:' 별이 ',xp:20,gold:99999,levels:{'0:1':30}}},{cookie:'__Host-ff-access=fake-access'});assert.equal(r.statusCode,200);assert.deepEqual(JSON.parse(reqs.at(-1).opt.body),{p_action:'save',p_payload:{nickname:'별이',xp:20}});for(const payload of [{xp:49501},{xp:-1},{xp:1.5},{nickname:'',xp:0},{nickname:'<script>',xp:0}])assert.equal((await call(guardian,{action:'save',owner:uid,payload},{cookie:'__Host-ff-access=fake-access'})).statusCode,400);const q=await call(guardian,{action:'save',owner:uid,payload:{xp:21}},{cookie:'__Host-ff-access=fake-access'});assert.equal(q.statusCode,200);assert.equal(JSON.parse(reqs.at(-1).opt.body).p_payload.nickname,undefined)});
