const {test}=require('node:test'),assert=require('node:assert/strict'),vm=require('node:vm'),fs=require('node:fs');
const flush=()=>new Promise(r=>setImmediate(r));
async function client({record=null,cache=null,configured=true,saveFails=false,guardianSync=null,adventureActive=false}={}){
 const nodes=new Map(),store=new Map(),sent=[],user={id:'account-A',email:'player@example.invalid'};let snapshot={levels:{'0:1':5},essence:15},inBattle=false,paused=false;
 if(cache)store.set('ff_account_pending_account-A',JSON.stringify(cache));
 function el(s){if(!nodes.has(s))nodes.set(s,{hidden:false,disabled:false,textContent:'',value:'',open:false,dataset:{},classList:{toggle(){}},focus(){},addEventListener(){},showModal(){this.open=true},close(){this.open=false}});return nodes.get(s)}
 const game={snapshot:()=>structuredClone(snapshot),guestSnapshot:()=>({levels:{'0:1':5},essence:15}),inBattle:()=>inBattle,pause:()=>{paused=true},apply:(v)=>{snapshot=structuredClone(v)},guest:()=>{snapshot={levels:{'0:1':5},essence:15}}};
 const w={ForgeGame:game,ForgeGuardianSync:guardianSync,ForgeAdventure:{active:()=>adventureActive,accountChanged(){},accountReady(){}}};const ctx=vm.createContext({window:w,document:{querySelector:el,querySelectorAll:()=>[],activeElement:null},addEventListener(){},localStorage:{getItem:k=>store.get(k)||null,setItem:(k,v)=>store.set(k,v)},URL,URLSearchParams,location:{search:'',href:'https://randomfortune-game.vercel.app/'},history:{state:null,replaceState(){}},AbortSignal,console,fetch:async(url,opt)=>{const b=JSON.parse(opt.body);sent.push({url,b});let status=200,data;if(url.endsWith('/account'))data={configured,user:configured?user:null};else if(b.action==='load')data={record};else if(saveFails){status=409;data={error:'CONFLICT',message:'저장 충돌'}}else data={record:{data:b.data,revision:(b.revision||0)+1}};return{ok:status===200,status,json:async()=>data}}});vm.runInContext(fs.readFileSync('public/account.js','utf8'),ctx);await flush();await flush();return{nodes,store,sent,w,snapshot:()=>snapshot,paused:()=>paused,el};
}
test('unconfigured auth keeps guest growth and does not send passwords or saves',async()=>{const c=await client({configured:false});assert.equal(c.w.ForgeAccount.allowed(),true);assert.equal(c.snapshot().essence,15);assert.equal(c.el('#accountSetup').hidden,false);assert.equal(c.sent.length,1)});
test('new account asks before importing guest progress and saves once after choice',async()=>{const c=await client();assert.equal(c.w.ForgeAccount.allowed(),false);assert.equal(c.el('#accountChoice').hidden,false);assert.equal(c.sent.some(r=>r.b.action==='save'),false);await c.el('#importGuest').onclick();assert.equal(c.snapshot().essence,15);assert.equal(c.w.ForgeAccount.allowed(),true);assert.equal(c.sent.filter(r=>r.b.action==='save').length,1)});
test('existing cloud progress takes precedence and does not auto-merge guest essence',async()=>{const c=await client({record:{revision:7,data:{levels:{'1:1':3},essence:8}}});assert.equal(c.snapshot().essence,8);assert.equal(c.snapshot().levels['0:1'],undefined);assert.equal(c.w.ForgeAccount.allowed(),true);assert.equal(c.sent.some(r=>r.b.action==='save'),false)});
test('unsaved cached progress with stale revision blocks battle without overwriting server',async()=>{const c=await client({record:{revision:9,data:{levels:{},essence:7}},cache:{revision:8,dirty:true,data:{levels:{'0:1':3},essence:40}}});assert.equal(c.w.ForgeAccount.allowed(),false);assert.equal(c.snapshot().essence,40);assert.equal(c.el('#cloudReload').hidden,false);assert.equal(c.sent.some(r=>r.b.action==='save'),false)});
test('save conflict retains local progress, pauses battle, and blocks logout',async()=>{const c=await client({record:{revision:2,data:{levels:{},essence:120}},saveFails:true});c.w.ForgeAccount.changed();await flush();assert.equal(c.w.ForgeAccount.allowed(),false);assert.equal(c.paused(),true);assert.equal(c.el('#accountLogout').disabled,true);assert.equal(JSON.parse(c.store.get('ff_account_pending_account-A')).dirty,true)});

test('migrated accounts still sync companion while suppressing legacy currency writes',async()=>{const loads=[];let changes=0;const guardianSync={reset(){},load:async id=>loads.push(id),changed:()=>changes++};const c=await client({record:{revision:3,data:{levels:{},essence:20}},guardianSync,adventureActive:true});assert.deepEqual(loads,['account-A']);c.w.ForgeAccount.changed();await flush();assert.equal(changes,1);assert.equal(c.sent.some(r=>r.b.action==='save'),false)});
