const {test}=require('node:test'),assert=require('node:assert/strict'),vm=require('node:vm'),fs=require('node:fs');
function audio({unsupported=false,storageFails=false,muted=false,musicMuted,sfxMuted}={}){const handlers={},timers=new Map(),nodes=[],contexts=[],stored=new Map([['ff_muted',muted?'1':'0']]);if(musicMuted!==undefined)stored.set("ff_music_muted",musicMuted?"1":"0");if(sfxMuted!==undefined)stored.set("ff_sfx_muted",sfxMuted?"1":"0");let seq=0;const buttons=[0,1].map(()=>({attrs:{},addEventListener(k,f){this.click=f},setAttribute(k,v){this.attrs[k]=v}}));const controls=Object.fromEntries(['musicToggle','sfxToggle','closeSoundSettings'].map(k=>[k,{attrs:{},addEventListener(k,f){this.click=f},setAttribute(k,v){this.attrs[k]=v}}]));const dialog={open:false,showModal(){this.open=true},close(){this.open=false}};const param=()=>({value:0,setValueAtTime(){},linearRampToValueAtTime(){},exponentialRampToValueAtTime(){},setTargetAtTime(){}});function node(){const n={gain:param(),frequency:param(),detune:param(),connect(){},disconnect(){this.disconnected=true},start(){this.started=true},stop(){this.stopped=true}};nodes.push(n);return n}class AC{constructor(){this.currentTime=2;this.sampleRate=8000;this.state='running';this.destination={};contexts.push(this)}createGain(){return node()}createOscillator(){return node()}createBufferSource(){return node()}createBiquadFilter(){return node()}createBuffer(c,n){return{getChannelData:()=>new Float32Array(n)}}resume(){this.state='running';return Promise.resolve()}suspend(){this.state='suspended';return Promise.resolve()}}
 const doc={hidden:false,querySelector:s=>s==="#soundSettingsDialog"?dialog:controls[s.slice(1)],querySelectorAll:()=>buttons,addEventListener:(k,f)=>{handlers[k]=f}},win=unsupported?{}:{AudioContext:AC};const ctx=vm.createContext({window:win,document:doc,localStorage:{getItem:k=>{if(storageFails)throw Error();return stored.get(k)},setItem:(k,v)=>{if(storageFails)throw Error();stored.set(k,v)}},addEventListener:(k,f)=>{handlers[k]=f},setInterval:f=>{timers.set(++seq,f);return seq},clearInterval:id=>timers.delete(id),Math,Promise});vm.runInContext(fs.readFileSync('public/audio.js','utf8'),ctx);return{win,doc,handlers,timers,nodes,contexts,buttons,stored,controls,dialog}}
test('audio starts after interaction once; all uploaded effects schedule real nodes',()=>{const a=audio();assert.equal(a.contexts.length,0);a.handlers.pointerdown();a.handlers.pointerdown();assert.equal(a.contexts.length,1);assert.equal(a.timers.size,1);const before=a.nodes.length;for(const [name,fn]of Object.entries(a.win.SFX))fn(name==='hit'?'fire':true);assert.ok(a.nodes.length>before);for(const n of a.nodes)if(n.onended){n.onended();assert.equal(n.disconnected,true)}});
test('settings opens without changing audio; music and effects switch independently',()=>{const a=audio();a.handlers.pointerdown();a.buttons[0].click();assert.equal(a.dialog.open,true);assert.equal(a.timers.size,1);a.controls.musicToggle.click();assert.equal(a.stored.get('ff_music_muted'),'1');assert.equal(a.timers.size,0);let n=a.nodes.length;a.win.SFX.summon();assert.ok(a.nodes.length>n);a.controls.sfxToggle.click();n=a.nodes.length;a.win.SFX.summon();assert.equal(a.nodes.length,n);assert.equal(a.stored.get('ff_sfx_muted'),'1');a.controls.musicToggle.click();assert.equal(a.timers.size,1);assert.equal(a.win.ForgeAudio.state().sfx,false);a.controls.closeSoundSettings.click();assert.equal(a.dialog.open,false)});
test('all four saved channel combinations are restored and effects never change the music choice',()=>{for(const musicMuted of [false,true])for(const sfxMuted of [false,true]){const a=audio({musicMuted,sfxMuted});a.handlers.pointerdown();assert.equal(a.timers.size,musicMuted?0:1);const n=a.nodes.length;a.win.SFX.fuse();assert.equal(a.nodes.length>n,!sfxMuted);assert.equal(a.controls.musicToggle.attrs['aria-pressed'],String(!musicMuted));assert.equal(a.controls.sfxToggle.attrs['aria-pressed'],String(!sfxMuted))}});
test('turning off effects leaves music voices connected and scheduled',()=>{const a=audio();a.handlers.pointerdown();const music=a.nodes.filter(n=>n.onended);a.win.SFX.summon();const effects=a.nodes.filter(n=>n.onended&&!music.includes(n));a.win.ForgeAudio.setSfx(false);assert.equal(a.timers.size,1);assert.ok(music.every(n=>!n.disconnected));assert.ok(effects.every(n=>n.disconnected));a.win.ForgeAudio.setMusic(false);assert.ok(music.every(n=>n.disconnected))});
test('foreground preserves music off while allowing effects',async()=>{const a=audio({musicMuted:true,sfxMuted:false});a.handlers.pointerdown();a.doc.hidden=true;a.handlers.visibilitychange();a.doc.hidden=false;a.handlers.visibilitychange();await Promise.resolve();assert.equal(a.timers.size,0);const n=a.nodes.length;a.win.SFX.summon();assert.ok(a.nodes.length>n)});
test('hidden page suspends sound and foreground schedules one music loop',async()=>{const a=audio();a.handlers.pointerdown();a.doc.hidden=true;a.handlers.visibilitychange();assert.equal(a.contexts[0].state,'suspended');assert.equal(a.timers.size,0);const n=a.nodes.length;a.win.SFX.ultimate();assert.equal(a.nodes.length,n);a.doc.hidden=false;a.handlers.visibilitychange();await Promise.resolve();assert.equal(a.contexts[0].state,'running');assert.equal(a.timers.size,1)});
test('unsupported audio and blocked storage never crash gameplay; saved mute is honored',()=>{const a=audio({unsupported:true,storageFails:true});assert.doesNotThrow(()=>a.handlers.pointerdown());assert.doesNotThrow(()=>a.win.SFX.fuse());assert.equal(a.buttons[0].disabled,true);const b=audio({muted:true});b.handlers.pointerdown();assert.equal(b.timers.size,0);const c=audio({storageFails:true});assert.doesNotThrow(()=>{c.handlers.pointerdown();c.win.ToggleMute()})});
test('pop music scheduler advances beats without duplicate notes and recovers after a delayed timer',()=>{const a=audio();a.win.ForgeAudio.setScene('battle');a.handlers.pointerdown();const tick=[...a.timers.values()][0],first=a.nodes.length;tick();assert.equal(a.nodes.length,first);a.contexts[0].currentTime+=.3;tick();assert.ok(a.nodes.length>first);a.contexts[0].currentTime+=30;const before=a.nodes.length;tick();assert.ok(a.nodes.length-before<40);const scheduled=a.nodes.filter(n=>n.started);a.win.ToggleMute();assert.ok(scheduled.every(n=>n.stopped));});

test('music scenes stop old voices, keep one scheduler and preserve mute preferences',()=>{const a=audio();a.handlers.pointerdown();const old=a.nodes.filter(n=>n.onended);a.win.ForgeAudio.setScene('battle');assert.equal(a.win.ForgeAudio.state().scene,'battle');assert.ok(old.every(n=>n.disconnected));assert.equal(a.timers.size,1);a.win.ForgeAudio.setScene('battle');assert.equal(a.timers.size,1);a.win.ForgeAudio.setMusic(false);a.win.ForgeAudio.setScene('lobby');assert.equal(a.timers.size,0);assert.equal(a.win.ForgeAudio.state().scene,'lobby');a.win.ForgeAudio.setMusic(true);assert.equal(a.timers.size,1)});
