const {test}=require('node:test');const assert=require('node:assert/strict');const vm=require('node:vm');const fs=require('node:fs');
function setup(){let observer,pop,now=1000;const messages=[];const elements={};const history={state:null,back(){this.backs=(this.backs||0)+1},pushState(s){this.state=s;this.pushes=(this.pushes||0)+1}};let battle=false;
function el(id,tagName='DIALOG'){return elements[id]={id,tagName,open:false,hidden:true,style:{display:'none'},showModal(){this.open=true},close(){this.open=false},dispatchEvent(e){if(this.cancel)this.cancel(e)},click(){this.action?.()}}}
for(const id of ['shopHub','unitAlbumDialog','albumDetailDialog','unitDrawDialog'])el(id);
for(const id of ['drawer','recipeOverlay','leaveBattle','homeButton','cancelLeave','resultScreen'])el(id,'DIV');
elements.homeButton.action=()=>elements.leaveBattle.hidden=false;elements.leaveBattle.style.display='block';elements.cancelLeave.action=()=>elements.leaveBattle.hidden=true;
const context={Date:{now:()=>now},toast:message=>messages.push(message),document:{body:{},getElementById:id=>elements[id],querySelectorAll:()=>Object.values(elements).filter(e=>e.tagName==='DIALOG'&&e.open)},history,location:{href:'https://game.test/'},getComputedStyle:e=>e.style,Event,MutationObserver:class{constructor(cb){observer=cb}observe(){}},addEventListener:(name,cb)=>{if(name==='popstate')pop=cb},openModal:id=>{elements[id.slice(1)].style.display='block';elements[id.slice(1)].hidden=false},closeModal:id=>elements[id.slice(1)].style.display='none',window:{ForgeGame:{inBattle:()=>battle}}};vm.runInNewContext(fs.readFileSync('public/back-navigation.js','utf8'),context);
return {elements,history,messages,advance:ms=>now+=ms,sync:()=>observer(),back:()=>pop(),battle:()=>battle=true};}
test('Back restores replaced shop and closes nested detail one level at a time',()=>{const s=setup(),e=s.elements;e.shopHub.showModal();s.sync();e.shopHub.close();e.unitAlbumDialog.showModal();s.sync();e.albumDetailDialog.showModal();s.sync();s.back();assert.equal(e.albumDetailDialog.open,false);assert.equal(e.unitAlbumDialog.open,true);s.back();assert.equal(e.unitAlbumDialog.open,false);assert.equal(e.shopHub.open,true);s.back();assert.equal(e.shopHub.open,false);assert.equal(s.history.pushes,4)});
test('Back respects busy cancel handlers and does not leave the page',()=>{const s=setup(),e=s.elements;e.unitDrawDialog.showModal();e.unitDrawDialog.cancel=event=>event.preventDefault();s.sync();s.back();assert.equal(e.unitDrawDialog.open,true);assert.equal(s.history.pushes,2)});
test('Battle Back warns once and a second press within two seconds allows exit',()=>{const s=setup();s.battle();s.back();assert.deepEqual(s.messages,['한 번 더 누르면 종료됩니다']);assert.equal(s.elements.leaveBattle.hidden,true);assert.equal(s.history.backs,undefined);s.advance(1000);s.back();assert.equal(s.history.backs,1)});
test('Expired warning and menu navigation require a fresh exit confirmation',()=>{const s=setup();s.back();s.advance(2100);s.back();assert.equal(s.messages.length,2);assert.equal(s.history.backs,undefined);s.elements.shopHub.showModal();s.sync();s.back();s.back();assert.equal(s.messages.length,3);assert.equal(s.history.backs,undefined)});
