const {test}=require('node:test');const assert=require('node:assert/strict');const vm=require('node:vm');const fs=require('node:fs');
const noop=()=>{};function game(){const els=new Map();const context2d=new Proxy({createLinearGradient:()=>({addColorStop:noop}),createRadialGradient:()=>({addColorStop:noop})},{get:(t,p)=>t[p]||noop});function el(id){if(!els.has(id))els.set(id,{style:{},dataset:{},classList:{toggle:noop},textContent:'',innerHTML:'',hidden:false,focus:noop,setAttribute:noop,addEventListener:noop,getContext:()=>context2d,querySelectorAll:()=>[]});return els.get(id)}const ctx=vm.createContext({document:{querySelector:el,querySelectorAll:()=>[],hidden:false},innerWidth:390,innerHeight:844,devicePixelRatio:1,addEventListener:noop,requestAnimationFrame:noop,performance:{now:()=>0},setTimeout:()=>1,clearTimeout:noop,console,Math});vm.runInContext(fs.readFileSync('public/game.js','utf8'),ctx);return{run:s=>vm.runInContext(s,ctx),els}}
test('T2 and T3 consume exactly three of the correct class and tier',()=>{const g=game();g.run('units=[0,1,2].map((type,slot)=>({type,slot,lv:1,cd:0}));craftRecipe(0)');assert.equal(g.run('units.length'),1);assert.equal(g.run('units[0].lv'),2);assert.equal(g.run('recipeReady(RECIPES[0])'),false)});
test('ZERO requires two FROST, not one',()=>{const g=game();g.run('units=[10,9].map((type,slot)=>({type,slot,lv:3,cd:0}))');assert.equal(g.run('recipeReady(RECIPES[11])'),false);g.run('units.push({type:10,slot:2,lv:3});craftRecipe(11)');assert.equal(g.run('units.length'),1);assert.equal(g.run('units[0].name'),'ZERO')});
test('all six legendary recipes consume real materials',()=>{for(let i=6;i<12;i++){const g=game();g.run(`units=RECIPES[${i}].parts.map((name,slot)=>({type:U.findIndex(u=>u.n===name),lv:3,slot,cd:0}));craftRecipe(${i})`);assert.equal(g.run('units.length'),1);assert.equal(g.run('units[0].lv'),4);assert.equal(g.run('units[0].name'),g.run(`RECIPES[${i}].name`))}});
test('all mythic recipes consume legendary units and create one fighting unit',()=>{for(let i=12;i<15;i++){const g=game();g.run(`units=RECIPES[${i}].special.map((name,slot)=>({type:SPECIALS[name].base,lv:4,name,slot,cd:0}));craftRecipe(${i})`);assert.equal(g.run('units.length'),1);assert.equal(g.run('units[0].lv'),5);g.run('fire(units[0],{x:0,y:0,hp:1000})');assert.ok(g.run('shots[0].dmg')>100);assert.equal(g.run(`recipeReady(RECIPES[${i}])`),false)}});
test('recipe close works and stale selection is cleared when consumed',()=>{const g=game();g.run("openRecipes();document.querySelector('#closeRecipe').onclick()");assert.equal(g.els.get('#recipeOverlay').style.display,'none');g.run('units=[0,1,2].map((type,slot)=>({type,slot,lv:1}));S.sel=units[1];craftRecipe(0)');assert.equal(g.run('units.includes(S.sel)'),true)});
test('80 monsters ends battle; reset clears units, projectiles and economy',()=>{const g=game();g.run('started=true;S.spawn=30;mobs=Array.from({length:80},()=>({hp:100,max:100,p:0,hit:0,stun:0,slow:0}));update(.01)');assert.equal(g.run('ended'),true);g.run('resetGame()');assert.equal(g.run('units.length'),4);assert.equal(g.run('mobs.length'),0);assert.equal(g.run('S.coin'),80);assert.equal(g.run('ended'),false)});
test('wave 30 victory waits for last enemy to die',()=>{const g=game();g.run('S.wave=30;S.spawn=30;S.t=25;S.stageStart=1;mobs=[{hp:100,max:100,p:0,hit:0,slow:0,stun:0}];update(.01)');assert.equal(g.run('ended'),false);g.run('mobs=[];update(.01)');assert.equal(g.run('ended'),true)});
test('all slots stay inside the monster lane on phone and desktop portrait layouts',()=>{const g=game();for(const [w,h] of [[320,568],[360,640],[390,844],[430,932],[1440,900]]){g.run(`W=${w};H=${h}`);assert.equal(g.run('Array.from({length:32},(_,i)=>slot(i)).every(p=>p.x>geometry().left+30&&p.x<geometry().right-30&&p.y>geometry().top+30&&p.y<geometry().bottom-30)'),true)}});
test('all hero render paths and game draw execute without errors',()=>{const g=game();g.run('for(let type=0;type<U.length;type++)for(let lv=1;lv<=5;lv++)body(ctx,0,0,{type,lv,slot:0},1,true);for(const name of Object.keys(SPECIALS))body(ctx,0,0,{type:SPECIALS[name].base,name,lv:5},1,true);draw()')});
test('PWA shell files and manifest icon sizes exist',()=>{const manifest=JSON.parse(fs.readFileSync('public/manifest.webmanifest'));assert.equal(manifest.display,'standalone');for(const i of manifest.icons)assert.ok(fs.existsSync('public'+i.src));const sw=fs.readFileSync('public/sw.js','utf8');for(const s of [...sw.matchAll(/'\/(.*?)'/g)].map(x=>x[1]).filter(Boolean))assert.ok(fs.existsSync('public/'+s),s)});
