const {test}=require('node:test');const assert=require('node:assert/strict');const vm=require('node:vm');const fs=require('node:fs');
const noop=()=>{};function game(storage){const els=new Map();const context2d=new Proxy({createLinearGradient:()=>({addColorStop:noop}),createRadialGradient:()=>({addColorStop:noop})},{get:(t,p)=>t[p]||noop});function el(id){if(!els.has(id))els.set(id,{style:{},dataset:{},classList:{toggle:noop},textContent:'',innerHTML:'',hidden:false,focus:noop,setAttribute:noop,addEventListener:noop,getContext:()=>context2d,querySelectorAll:()=>[]});return els.get(id)}const ctx=vm.createContext({window:{},document:{querySelector:el,querySelectorAll:()=>[],hidden:false},innerWidth:390,innerHeight:844,devicePixelRatio:1,addEventListener:noop,requestAnimationFrame:noop,performance:{now:()=>0},setTimeout:()=>1,clearTimeout:noop,console,Math,...(storage?{localStorage:storage}:{})});vm.runInContext(fs.readFileSync('public/skills.js','utf8'),ctx);vm.runInContext(fs.readFileSync('public/game.js','utf8'),ctx);return{run:s=>vm.runInContext(s,ctx),els}}
test('T2 and T3 consume exactly three of the correct class and tier',()=>{const g=game();g.run('units=[0,1,2].map((type,slot)=>({type,slot,lv:1,cd:0}));craftRecipe(0)');assert.equal(g.run('units.length'),1);assert.equal(g.run('units[0].lv'),2);assert.equal(g.run('recipeReady(RECIPES[0])'),false)});
test('ZERO requires two FROST, not one',()=>{const g=game();g.run('units=[10,9].map((type,slot)=>({type,slot,lv:3,cd:0}))');assert.equal(g.run('recipeReady(RECIPES[11])'),false);g.run('units.push({type:10,slot:2,lv:3});craftRecipe(11)');assert.equal(g.run('units.length'),1);assert.equal(g.run('units[0].name'),'ZERO')});
test('all six legendary recipes consume real materials',()=>{for(let i=6;i<12;i++){const g=game();g.run(`units=RECIPES[${i}].parts.map((name,slot)=>({type:U.findIndex(u=>u.n===name),lv:3,slot,cd:0}));craftRecipe(${i})`);assert.equal(g.run('units.length'),1);assert.equal(g.run('units[0].lv'),4);assert.equal(g.run('units[0].name'),g.run(`RECIPES[${i}].name`))}});
test('all mythic recipes consume legendary units and create one fighting unit',()=>{for(let i=12;i<15;i++){const g=game();g.run(`units=RECIPES[${i}].special.map((name,slot)=>({type:SPECIALS[name].base,lv:4,name,slot,cd:0}));craftRecipe(${i})`);assert.equal(g.run('units.length'),1);assert.equal(g.run('units[0].lv'),5);g.run('fire(units[0],{x:0,y:0,hp:1000})');assert.ok(g.run('shots[0].dmg')>100);assert.equal(g.run(`recipeReady(RECIPES[${i}])`),false)}});
test('recipe close works and stale selection is cleared when consumed',()=>{const g=game();g.run("openRecipes();document.querySelector('#closeRecipe').onclick()");assert.equal(g.els.get('#recipeOverlay').style.display,'none');g.run('units=[0,1,2].map((type,slot)=>({type,slot,lv:1}));S.sel=units[1];craftRecipe(0)');assert.equal(g.run('units.includes(S.sel)'),true)});
test('80 monsters ends battle; reset clears units, projectiles and economy',()=>{const g=game();g.run('started=true;S.spawn=30;mobs=Array.from({length:80},()=>({hp:100,max:100,p:0,hit:0,stun:0,slow:0}));update(.01)');assert.equal(g.run('ended'),true);g.run('resetGame()');assert.equal(g.run('units.length'),4);assert.equal(g.run('mobs.length'),0);assert.equal(g.run('S.coin'),80);assert.equal(g.run('ended'),false)});
test('wave 30 victory waits for last enemy to die',()=>{const g=game();g.run('S.wave=30;S.spawn=30;S.t=25;S.stageStart=1;mobs=[{hp:100,max:100,p:0,hit:0,slow:0,stun:0}];update(.01)');assert.equal(g.run('ended'),false);g.run('mobs=[];update(.01)');assert.equal(g.run('ended'),true)});
test('all slots stay inside the monster lane on phone and desktop portrait layouts',()=>{const g=game();for(const [w,h] of [[320,568],[360,640],[390,844],[430,932],[1440,900]]){g.run(`W=${w};H=${h}`);assert.equal(g.run('Array.from({length:32},(_,i)=>slot(i)).every(p=>p.x>geometry().left+30&&p.x<geometry().right-30&&p.y>geometry().top+30&&p.y<geometry().bottom-30)'),true)}});
test('all hero render paths and game draw execute without errors',()=>{const g=game();g.run('for(let type=0;type<U.length;type++)for(let lv=1;lv<=5;lv++)body(ctx,0,0,{type,lv,slot:0},1,true);for(const name of Object.keys(SPECIALS))body(ctx,0,0,{type:SPECIALS[name].base,name,lv:5},1,true);draw()')});
test('PWA shell files and manifest icon sizes exist',()=>{const manifest=JSON.parse(fs.readFileSync('public/manifest.webmanifest'));assert.equal(manifest.display,'standalone');for(const i of manifest.icons)assert.ok(fs.existsSync('public'+i.src));const sw=fs.readFileSync('public/sw.js','utf8');for(const s of [...sw.matchAll(/'\/(.*?)'/g)].map(x=>x[1]).filter(Boolean))assert.ok(fs.existsSync('public/'+s),s)});
test('full catalog includes exactly 66 unique playable hero/tier entries',()=>{const g=game();assert.equal(g.run('catalogEntries().length'),66);assert.equal(g.run('new Set(catalogEntries().map(u=>u.type+":"+u.lv)).size'),66);assert.equal(g.run('catalogEntries().filter(u=>u.lv>=4).every(u=>RECIPES[u.recipe].name===u.name)'),true)});
test('every legendary and mythic recipe consumes its materials exactly once',()=>{const g=game();for(let i=0;i<g.run('RECIPES.length');i++){if(g.run(`RECIPES[${i}].tier`)<4)continue;g.run(`{const r=RECIPES[${i}];units=r.parts?r.parts.map((n,slot)=>({type:U.findIndex(u=>u.n===n),lv:3,slot,cd:0})):r.special.map((name,slot)=>({type:SPECIALS[name].base,lv:r.specialTier||4,name,slot,cd:0}));}`);assert.equal(g.run(`craftRecipe(${i})`),true);assert.equal(g.run('units.length'),1);assert.equal(g.run(`units[0].name===RECIPES[${i}].name`),true);assert.equal(g.run(`craftRecipe(${i})`),false)}});
test('partial materials stay in color, absent materials are grayscale, class materials show owned counts',()=>{const g=game();assert.match(g.run('materialHTML({type:10,lv:3},1,2)'),/mat partial/);assert.match(g.run('materialHTML({type:10,lv:3},0,2)'),/mat miss/);assert.match(g.run('materialHTML({type:10,lv:3},2,2)'),/mat have/);g.run('units=[{type:0,lv:1,slot:0}]');const html=g.run('recipeMaterials(RECIPES[0])');assert.match(html,/1<small> 보유/);assert.doesNotMatch(html,/\/ 3/)});
test('combine opens the entire codex even after a previous ready-only filter',()=>{const g=game();g.run("recipeFilter='ready';openRecipes()");assert.equal(g.run('recipeFilter'),'all');assert.equal((g.els.get('#recipeBook').innerHTML.match(/class="evolutionCard/g)||[]).length,66)});
test('loading the sprite atlas uses drawImage for every hero and tier',()=>{const g=game();g.run('atlasLoaded=true;for(const u of catalogEntries())body(ctx,0,0,u,1,true)')});

test('T1 summons exactly six types while T2 onward retains twelve per tier',()=>{const g=game();assert.equal(g.run('summonTypes.length'),6);assert.equal(g.run("['MELEE','RANGED','MAGIC'].every(cls=>summonTypes.filter(i=>U[i].cls===cls).length===2)"),true);assert.equal(g.run('[2,3,4,5].every(lv=>catalogEntries().filter(u=>u.lv===lv).length===12)'),true);assert.equal(g.run('catalogEntries().filter(u=>u.lv===1).length'),6);g.run('S.coin=100000;for(let i=0;i<32;i++)summon()');assert.equal(g.run('units.length'),32);assert.equal(g.run('units.every(u=>u.lv>1||summonTypes.includes(u.type))'),true);assert.equal(g.run('new Set(units.map(u=>u.slot)).size'),32)});
test('selling refunds 50 percent of actual invested cost and frees the slot exactly once',()=>{const g=game();g.run('started=true;units=[{type:0,lv:1,slot:5,invested:18}];S.sel=units[0];S.coin=0');assert.equal(g.run('sellSelected()'),true);assert.equal(g.run('S.coin'),9);assert.equal(g.run('units.length'),0);assert.equal(g.run('sellSelected()'),false);assert.equal(g.run('S.coin'),9)});
test('crafting carries the sum of ingredient costs into the resale price',()=>{const g=game();g.run('started=true;units=[{type:0,lv:1,slot:0,invested:10},{type:1,lv:1,slot:1,invested:14},{type:0,lv:1,slot:2,invested:18}];craftRecipe(0)');assert.equal(g.run('units[0].invested'),42);assert.equal(g.run('sellValue(units[0])'),21)});
function memoryStorage(seed={}){const data=new Map(Object.entries(seed));return{getItem:k=>data.get(k)??null,setItem:(k,v)=>data.set(k,String(v))}}
test('new player gets starter essence once and progression survives reload',()=>{const storage=memoryStorage(),g=game(storage);assert.equal(g.run('essence'),120);assert.equal(g.run('levelUpHero(0,1)'),true);assert.equal(g.run('essence'),108);const next=game(storage);assert.equal(next.run('getLv(0,1)'),2);assert.equal(next.run('essence'),108);assert.equal(next.run('getLv(0,2)'),1)});
test('skill slots require both hero level and tier',()=>{const g=game();for(let tier=1;tier<=6;tier++)for(let level=1;level<=30;level++){g.run(`heroLevels['0:${tier}']=${level}`);assert.equal(g.run(`skillRows({type:0,lv:${tier}}).filter(s=>s.unlocked).length`),Math.min(tier,Math.floor(level/5)))}});
test('upgrades apply to real battle projectiles after reset and respect tier separation',()=>{const g=game();g.run('levelUpHero(0,1);started=true;resetGame();fire({type:0,lv:1,slot:0},{x:0,y:0,hp:100})');assert.ok(Math.abs(g.run('shots[0].dmg')-7.35)<1e-10);assert.equal(g.run('getLv(0,2)'),1)});
test('upgrade rejects insufficient funds, max level, invalid starter, and active battle',()=>{const g=game();g.run('essence=0');assert.equal(g.run('levelUpHero(0,1)'),false);g.run('essence=10000;heroLevels["0:1"]=30');assert.equal(g.run('levelUpHero(0,1)'),false);assert.equal(g.run('levelUpHero(2,1)'),false);g.run('started=true');assert.equal(g.run('levelUpHero(1,1)'),false);assert.equal(g.run('essence'),10000)});
test('legacy saves migrate without losing levels, corrupted storage cannot crash startup',()=>{const storage=memoryStorage({ff_heroLevelsV2:'{"0:1":6}',ff_essence:'35'}),g=game(storage);assert.equal(g.run('getLv(0,1)'),6);assert.equal(g.run('essence'),155);const broken=game(memoryStorage({ff_progress_v3:'broken'}));assert.equal(broken.run('getLv(0,1)'),1);assert.equal(broken.run('storageAvailable'),false)});
test('finish rewards are granted only once and lobby preserves growth',()=>{const g=game();g.run('started=true;S.wave=8;finish(false)');const value=g.run('essence');g.run('finish(false)');assert.equal(g.run('essence'),value);g.run('goLobby();levelUpHero(0,1);started=true;resetGame()');assert.equal(g.run('getLv(0,1)'),2)});

test('account growth storage never overwrites original guest progression',()=>{const storage=memoryStorage(),g=game(storage);g.run('levelUpHero(0,1)');const guest=storage.getItem('ff_progress_v3');g.run('window.ForgeGame.apply({levels:{"1:1":2},essence:200},"account-A");levelUpHero(1,1)');assert.equal(storage.getItem('ff_progress_v3'),guest);assert.equal(JSON.parse(storage.getItem('ff_progress_account_account-A')).levels['1:1'],3);g.run('window.ForgeGame.guest()');assert.equal(g.run('getLv(0,1)'),2);assert.equal(g.run('essence'),108)});
test('unresolved account state blocks new battles and upgrades',()=>{const g=game();g.run('window.ForgeAccount={allowed:()=>false,open:()=>{}};document.querySelector("#startGame").onclick()');assert.equal(g.run('started'),false);assert.equal(g.run('levelUpHero(0,1)'),false);assert.equal(g.run('essence'),120)});

test('run upgrades cost 10 through 100, add one percent each and stop at ten',()=>{const g=game();g.run('started=true;units=[{type:0,lv:1,slot:0,invested:10}];S.sel=units[0];S.coin=1000');const base=g.run('battleAttack(S.sel)');for(let n=1;n<=10;n++){assert.equal(g.run('battleUpgradeCost(S.sel)'),n*10);assert.equal(g.run('upgradeBattleSelected()'),true);assert.ok(Math.abs(g.run('battleAttack(S.sel)')-base*(1+n/100))<1e-9)}assert.equal(g.run('S.coin'),450);assert.equal(g.run('upgradeBattleSelected()'),false);g.run('fire(S.sel,{hp:100,x:0,y:0})');assert.ok(Math.abs(g.run('shots[0].dmg')-base*1.1)<1e-9);assert.equal(g.run('sellValue(S.sel)'),5)});
test('run upgrades apply to future identical heroes, isolate tiers, and never enter saves',()=>{const g=game();g.run('started=true;units=[{type:0,lv:1,slot:0}];S.sel=units[0];S.coin=100;upgradeBattleSelected()');assert.equal(g.run('battleUpgradeLevel({type:0,lv:1})'),1);assert.equal(g.run('battleUpgradeLevel({type:0,lv:2})'),0);assert.equal(g.run('battleUpgradeLevel({type:1,lv:1})'),0);assert.equal(g.run('JSON.stringify(window.ForgeGame.snapshot()).includes("battleUpgrades")'),false);for(const action of ['finish(true)','finish(false)','goLobby()','resetGame()']){g.run('ended=false;started=true;battleUpgrades={"0:1":5};'+action);assert.equal(g.run('battleUpgradeLevel({type:0,lv:1})'),0)}});
test('run upgrade rejects insufficient coins, pause, stale selection and blocked auth',()=>{const g=game();g.run('started=true;units=[{type:0,lv:1,slot:0}];S.sel=units[0];S.coin=9');assert.equal(g.run('upgradeBattleSelected()'),false);g.run('S.coin=100;paused=true');assert.equal(g.run('upgradeBattleSelected()'),false);g.run('paused=false;window.ForgeAccount={allowed:()=>false}');assert.equal(g.run('upgradeBattleSelected()'),false);g.run('window.ForgeAccount=null;units=[]');assert.equal(g.run('upgradeBattleSelected()'),false);assert.equal(g.run('S.coin'),100)});

test('summon tier boundaries and full bucket distribution exactly match displayed odds',()=>{const g=game();assert.equal(g.run('SUMMON_WEIGHTS.reduce((a,b)=>a+b,0)'),10000);assert.equal(g.run('JSON.stringify(Array.from({length:10000},(_,i)=>rollSummonTier(()=>i/10000)).reduce((a,t)=>(a[t-1]++,a),[0,0,0,0,0,0]))'),'[7000,2000,700,250,45,5]');for(let tier=1;tier<=6;tier++){g.run(`Math.random=()=>${[0,.71,.91,.975,.996,.9996][tier-1]};units=[];S.coin=100;summon()`);assert.equal(g.run('units[0].lv'),tier);assert.equal(g.run('Number.isFinite(battleAttack(units[0]))'),true)}});
test('all skill ranks persist, cap at ten and consume increasing essence without affecting guest save',()=>{const storage=memoryStorage(),g=game(storage);g.run('heroLevels["9:6"]=30;essence=100000');for(let i=0;i<6;i++){for(let n=1;n<10;n++)assert.equal(g.run(`levelUpSkill(9,6,${i})`),true);assert.equal(g.run(`levelUpSkill(9,6,${i})`),false)}const next=game(storage);assert.equal(next.run('getLv(9,6)'),30);assert.equal(next.run('skillRank({type:9,lv:6},5)'),10);assert.equal(next.run('essence'),100000-6*60*45);next.run('started=true');assert.equal(next.run('levelUpSkill(0,1,0)'),false)});
test('every hero active effect damages enemies and every rank is stronger',()=>{const g=game();g.run('heroLevels=Object.fromEntries(catalogEntries().map(u=>[lvKey(u.type,u.lv),30]));units=[{type:0,lv:6,slot:0}];');for(let type=0;type<12;type++)for(let i=0;i<6;i++){g.run(`units[0].type=${type};mobs=[{...slot(0),x:slot(0).x+20,hp:100000000,max:100000000,p:0,stun:0,slow:0}];`);assert.equal(g.run(`skillStats(HERO_SKILLS[${type}][${i}],10).power>skillStats(HERO_SKILLS[${type}][${i}],1).power`),true);if(g.run(`HERO_SKILLS[${type}][${i}].active`)){g.run(`castHeroSkill(units[0],HERO_SKILLS[${type}][${i}],10,mobs[0])`);assert.ok(g.run('mobs[0].hp')<100000000)}}});
test('chain stuns and shocks nearby enemies but never jumps to distant enemies',()=>{const g=game();g.run('units=[{type:9,lv:2,slot:0}];mobs=[0,30,60,500].map(x=>({x,y:0,hp:100000,max:100000,p:0,stun:0}));castHeroSkill(units[0],HERO_SKILLS[9][0],10,mobs[0])');assert.equal(g.run('mobs.slice(0,3).every(m=>m.hp<100000&&m.stun>0&&m.dotTime>0)'),true);assert.equal(g.run('mobs[3].hp'),100000)});
test('support aura range, strongest-only stacking, removal and cooldown acceleration',()=>{const g=game();g.run('heroLevels={"11:6":30};heroSkills={"11:6:1":10,"11:6:2":10,"11:6:3":10,"11:6:4":10};units=[{type:0,lv:1,slot:0},{type:11,lv:6,slot:1},{type:11,lv:6,slot:2}];');assert.ok(g.run('skillModifiers(units[0]).attack')>.29);assert.ok(g.run('skillModifiers(units[0]).attack')<.31);g.run('prepareSkills(units[0]);units[0].skillCD[0]=5;tickHeroSkills(units[0],1)');assert.ok(g.run('units[0].skillCD[0]')<4);assert.ok(g.run('units[0].mp')>5);g.run('units=units.slice(0,1)');assert.equal(g.run('skillModifiers(units[0]).attack'),0)});
test('MP and cooldown gate automatic skills and combination resets MP',()=>{const g=game();g.run('heroLevels={"0:1":5};units=[{type:0,lv:1,slot:0}];mobs=[{...slot(0),hp:10000,max:10000,p:0}];tickHeroSkills(units[0],0)');assert.equal(g.run('mobs[0].hp'),10000);g.run('units[0].mp=100;tickHeroSkills(units[0],0)');assert.ok(g.run('mobs[0].hp')<10000);assert.equal(g.run('units[0].mp'),65);const hp=g.run('mobs[0].hp');g.run('tickHeroSkills(units[0],0)');assert.equal(g.run('mobs[0].hp'),hp);g.run('units=[0,1,0].map((type,slot)=>({type,lv:1,slot,mp:100,skillCD:[1]}));craftRecipe(0)');assert.equal(g.run('units[0].mp'),0);assert.equal(g.run('units[0].skillCD.length'),6)});
test('ultimate is absent and sixth tier uses valid atlas bounds',()=>{const html=fs.readFileSync('public/index.html','utf8');assert.doesNotMatch(html,/별빛 강림|id="ult"/);const g=game();g.run('atlasLoaded=true;catalogEntries().filter(u=>u.lv===6).forEach(u=>body(ctx,0,0,u,1,true))')});
