const {test}=require('node:test');const assert=require('node:assert/strict');const vm=require('node:vm');const fs=require('node:fs');
const noop=()=>{};function game(storage){const els=new Map();const context2d=new Proxy({createLinearGradient:()=>({addColorStop:noop}),createRadialGradient:()=>({addColorStop:noop})},{get:(t,p)=>t[p]||noop});function el(id){if(!els.has(id))els.set(id,{style:{},dataset:{},classList:{toggle:noop},textContent:'',innerHTML:'',hidden:false,focus:noop,setAttribute:noop,addEventListener:noop,getContext:()=>context2d,querySelectorAll:()=>[],insertAdjacentHTML:noop});return els.get(id)}const ctx=vm.createContext({window:{},document:{querySelector:el,querySelectorAll:()=>[],hidden:false},innerWidth:390,innerHeight:844,devicePixelRatio:1,addEventListener:noop,requestAnimationFrame:noop,performance:{now:()=>0},setTimeout:()=>1,clearTimeout:noop,console,Math,...(storage?{localStorage:storage}:{})});for(const file of ['adventure-data','evolution','hero-art','special-skills','skills','combat-fx','random-forge','interface','guardian'])vm.runInContext(fs.readFileSync('public/'+file+'.js','utf8'),ctx);vm.runInContext(fs.readFileSync('public/game.js','utf8'),ctx);return{run:s=>vm.runInContext(s,ctx),els}}
test('guardian keeps permanent name and level while restoration resets every battle',()=>{const g=game();g.run("guardianMeta={nickname:'나의별',xp:49500};guardianRun.xp=600;resetGame()");assert.equal(g.run('guardianLevel(guardianMeta)'),100);assert.equal(g.run('guardianMeta.nickname'),'나의별');assert.equal(g.run('guardianStage()'),1);assert.equal(g.run('units.length'),4);assert.equal(g.run('window.ForgeGame.snapshot().guardian.xp'),49500)});
test('guardian advances through five restoration stages and each kill awards once',()=>{const g=game();g.run('guardianMeta.xp=0;for(let i=0;i<150;i++)guardianKill({})');assert.equal(g.run('guardianStage()'),2);g.run('for(let i=0;i<450;i++)guardianKill({})');assert.equal(g.run('guardianStage()'),5);g.run('const victim={hp:1,x:0,y:0};hit(victim,10,"skill");hit(victim,10,"skill")');assert.equal(g.run('guardianMeta.xp'),601)});
test('guardian manual support requires restoration, mana and a nearby ally; pause blocks it',()=>{const g=game();g.run('units=[{type:8,lv:1,slot:14,mp:0,skillCD:[20,0,0,0,0,0,0]}];started=true;guardianRun.mp=100');assert.equal(g.run('castGuardian()'),false);g.run('guardianRun.xp=600;paused=true');assert.equal(g.run('castGuardian()'),false);g.run('paused=false');assert.equal(g.run('castGuardian()'),true);assert.equal(g.run('units[0].skillCD[0]'),17);assert.equal(g.run('guardianRun.mp'),40);assert.equal(g.run('castGuardian()'),false)});
test('80 monsters ends battle; reset clears units, projectiles and economy',()=>{const g=game();g.run('started=true;S.spawn=30;mobs=Array.from({length:80},()=>({hp:100,max:100,p:0,hit:0,stun:0,slow:0}));update(.01)');assert.equal(g.run('ended'),true);g.run('resetGame()');assert.equal(g.run('units.length'),4);assert.equal(g.run('mobs.length'),0);assert.equal(g.run('S.coin'),80);assert.equal(g.run('ended'),false)});
test('wave 30 victory waits for last enemy to die',()=>{const g=game();g.run('S.wave=30;S.spawn=30;S.t=25;S.stageStart=1;mobs=[{hp:100,max:100,p:0,hit:0,slow:0,stun:0}];update(.01)');assert.equal(g.run('ended'),false);g.run('mobs=[];update(.01)');assert.equal(g.run('ended'),true)});
test('all slots stay inside the monster lane on phone and desktop portrait layouts',()=>{const g=game();for(const [w,h] of [[320,568],[360,640],[390,844],[430,932],[1440,900]]){g.run(`W=${w};H=${h}`);assert.equal(g.run('Array.from({length:32},(_,i)=>slot(i)).every(p=>p.x>geometry().left+30&&p.x<geometry().right-30&&p.y>geometry().top+30&&p.y<geometry().bottom-30)'),true)}});
test('PWA shell files and manifest icon sizes exist',()=>{const manifest=JSON.parse(fs.readFileSync('public/manifest.webmanifest'));assert.equal(manifest.display,'standalone');for(const i of manifest.icons)assert.ok(fs.existsSync('public'+i.src));const sw=fs.readFileSync('public/sw.js','utf8');for(const s of [...sw.matchAll(/'\/(.*?)'/g)].map(x=>x[1]).filter(Boolean))assert.ok(fs.existsSync('public/'+s),s)});
test('selling refunds 50 percent of actual invested cost and frees the slot exactly once',()=>{const g=game();g.run('started=true;units=[{type:0,lv:1,slot:5,invested:18}];S.sel=units[0];S.coin=0');assert.equal(g.run('sellSelected()'),true);assert.equal(g.run('S.coin'),9);assert.equal(g.run('units.length'),0);assert.equal(g.run('sellSelected()'),false);assert.equal(g.run('S.coin'),9)});
function memoryStorage(seed={}){const data=new Map(Object.entries(seed));return{getItem:k=>data.get(k)??null,setItem:(k,v)=>data.set(k,String(v))}}
test('new player gets starter essence once and progression survives reload',()=>{const storage=memoryStorage(),g=game(storage);assert.equal(g.run('essence'),120);assert.equal(g.run('levelUpHero(0,1)'),true);assert.equal(g.run('essence'),108);const next=game(storage);assert.equal(next.run('getLv(0,1)'),2);assert.equal(next.run('essence'),108);assert.equal(next.run('getLv(0,2)'),1)});
test('legacy saves migrate without losing levels, corrupted storage cannot crash startup',()=>{const storage=memoryStorage({ff_heroLevelsV2:'{"0:1":6}',ff_essence:'35'}),g=game(storage);assert.equal(g.run('getLv(0,1)'),6);assert.equal(g.run('essence'),155);const broken=game(memoryStorage({ff_progress_v3:'broken'}));assert.equal(broken.run('getLv(0,1)'),1);assert.equal(broken.run('storageAvailable'),false)});
test('finish rewards are granted only once and lobby preserves growth',()=>{const g=game();g.run('started=true;S.wave=8;finish(false)');const value=g.run('essence');g.run('finish(false)');assert.equal(g.run('essence'),value);g.run('goLobby();levelUpHero(0,1);started=true;resetGame()');assert.equal(g.run('getLv(0,1)'),2)});
test('account growth storage never overwrites original guest progression',()=>{const storage=memoryStorage(),g=game(storage);g.run('levelUpHero(0,1)');const guest=storage.getItem('ff_progress_v3');g.run('window.ForgeGame.apply({version:4,levels:{"1:1":2},essence:200},"account-A");levelUpHero(1,1)');assert.equal(storage.getItem('ff_progress_v3'),guest);assert.equal(JSON.parse(storage.getItem('ff_progress_account_account-A')).levels['1:1'],3);g.run('window.ForgeGame.guest()');assert.equal(g.run('getLv(0,1)'),2);assert.equal(g.run('essence'),108)});
test('unresolved account state blocks new battles and upgrades',()=>{const g=game();g.run('window.ForgeAccount={allowed:()=>false,open:()=>{}};document.querySelector("#startGame").onclick()');assert.equal(g.run('started'),false);assert.equal(g.run('levelUpHero(0,1)'),false);assert.equal(g.run('essence'),120)});
test('run upgrades cost 10 through 100, add one percent each and stop at ten',()=>{const g=game();g.run('started=true;units=[{type:0,lv:1,slot:0,invested:10}];S.sel=units[0];S.coin=1000');const base=g.run('battleAttack(S.sel)');for(let n=1;n<=10;n++){assert.equal(g.run('battleUpgradeCost(S.sel)'),n*10);assert.equal(g.run('upgradeBattleSelected()'),true);assert.ok(Math.abs(g.run('battleAttack(S.sel)')-base*(1+n/100))<1e-9)}assert.equal(g.run('S.coin'),450);assert.equal(g.run('upgradeBattleSelected()'),false);g.run('fire(S.sel,{hp:10000,max:10000,x:0,y:0})');assert.ok(Math.abs(g.run('combatAttack(S.sel)')-base*1.1)<1e-9);assert.equal(g.run('sellValue(S.sel)'),5)});
test('run upgrades apply to future identical heroes, isolate tiers, and never enter saves',()=>{const g=game();g.run('started=true;units=[{type:0,lv:1,slot:0}];S.sel=units[0];S.coin=100;upgradeBattleSelected()');assert.equal(g.run('battleUpgradeLevel({type:0,lv:1})'),1);assert.equal(g.run('battleUpgradeLevel({type:0,lv:2})'),0);assert.equal(g.run('battleUpgradeLevel({type:1,lv:1})'),0);assert.equal(g.run('JSON.stringify(window.ForgeGame.snapshot()).includes("battleUpgrades")'),false);for(const action of ['finish(true)','finish(false)','goLobby()','resetGame()']){g.run('guestReward=0;ended=false;started=true;battleUpgrades={"0:1":5};'+action);assert.equal(g.run('battleUpgradeLevel({type:0,lv:1})'),0)}});
test('run upgrade rejects insufficient coins, pause, stale selection and blocked auth',()=>{const g=game();g.run('started=true;units=[{type:0,lv:1,slot:0}];S.sel=units[0];S.coin=9');assert.equal(g.run('upgradeBattleSelected()'),false);g.run('S.coin=100;paused=true');assert.equal(g.run('upgradeBattleSelected()'),false);g.run('paused=false;window.ForgeAccount={allowed:()=>false}');assert.equal(g.run('upgradeBattleSelected()'),false);g.run('window.ForgeAccount=null;units=[]');assert.equal(g.run('upgradeBattleSelected()'),false);assert.equal(g.run('S.coin'),100)});
test('41 entries: six per growth tier, seventeen independent final forms, no sixth tier',()=>{const g=game();assert.equal(g.run('catalogEntries().length'),41);assert.equal(g.run('new Set(catalogEntries().map(u=>lvKey(u.type,u.lv))).size'),41);for(let tier=1;tier<=5;tier++)assert.equal(g.run(`catalogEntries().filter(u=>u.lv===${tier}).length`),tier===5?17:6);assert.equal(g.run('RECIPES.some(r=>r.tier>5)'),false)});
test('all recipes consume exactly three same-element lower-tier units and give the selected form',()=>{const g=game();g.run('started=true;window.ForgeAdventure={unlocked:()=>true,record:()=>{},final:()=>{}}');for(let i=0;i<g.run('RECIPES.length');i++){g.run(`{const r=RECIPES[${i}];units=r.parts.map((n,slot)=>({type:U.findIndex(u=>u.n===n),lv:r.partTier,slot,invested:10}));}`);assert.equal(g.run(`recipeReady(RECIPES[${i}])`),true);assert.equal(g.run(`craftRecipe(${i})`),true);assert.equal(g.run('units.length'),1);assert.equal(g.run('units[0].invested'),30);assert.equal(g.run('units[0].type'),g.run(`SPECIALS[RECIPES[${i}].name].base`));assert.equal(g.run(`craftRecipe(${i})`),false)}});
test('wrong elements and insufficient duplicate ingredients cannot craft',()=>{const g=game();g.run('started=true;units=[{type:8,lv:1,slot:0},{type:8,lv:1,slot:1},{type:10,lv:1,slot:2}]');assert.equal(g.run('craftRecipe(0)'),false);assert.equal(g.run('units.length'),3);assert.match(g.run('recipeMaterials(RECIPES[0])'),/mat partial/)});
test('growth retains every inherited skill and final skills unlock at 1, 10, 20; 30 awakens only first final',()=>{const g=game();for(let tier=1;tier<=4;tier++)assert.equal(g.run(`skillRows({type:8,lv:${tier}}).filter(s=>s.unlocked).length`),tier);for(const level of [1,9,10,19,20,29,30]){g.run(`heroLevels['8:5']=${level}`);assert.equal(g.run('skillRows({type:8,lv:5}).filter(s=>s.unlocked).length'),level<10?5:level<20?6:7)}g.run("heroLevels['8:5']=29");const before=g.run('skillStats(definitions({type:8,lv:5})[4],1,{type:8,lv:5}).power');g.run("heroLevels['8:5']=30");assert.equal(g.run('skillStats(definitions({type:8,lv:5})[4],1,{type:8,lv:5}).power'),before*1.5);assert.equal(g.run('skillStats(definitions({type:8,lv:5})[5],1,{type:8,lv:5}).awakened'),false)});
test('summon probabilities total 100 percent and every bucket returns a valid unit',()=>{const g=game();assert.equal(g.run('JSON.stringify(Array.from({length:10000},(_,i)=>rollSummonTier(()=>i/10000)).reduce((a,t)=>(a[t-1]++,a),[0,0,0,0,0]))'),'[7000,2000,700,250,50]');for(const r of [0,.71,.91,.975,.999]){g.run(`Math.random=()=>${r};units=[];S.coin=100;summon()`);assert.equal(g.run('validHero(units[0].type,units[0].lv)'),true)}});
test('all valid render paths, recipe dialog and growth dialog execute',()=>{const g=game();g.run('for(const u of catalogEntries())body(ctx,0,0,u,1,true);openRecipes();renderHeroLab();draw();document.querySelector("#closeRecipe").onclick()');assert.equal(g.els.get('#recipeOverlay').style.display,'none');assert.equal((g.els.get('#recipeBook').innerHTML.match(/class="evolutionCard/g)||[]).length,41)});
test('all active damage and control effects execute with finite enemy state',()=>{const g=game();g.run('heroLevels=Object.fromEntries(catalogEntries().map(u=>[lvKey(u.type,u.lv),30]));');for(let type=0;type<17;type++){g.run(`units=[{type:${type},lv:5,slot:0}];tickBattleStatus(0);`);for(let i=0;i<7;i++){g.run('mobs=[0,20,40].map((n)=>({...slot(0),x:slot(0).x+n,hp:1e7,max:1e7,p:.1,stun:0,slow:0}));skillZones=[];');if(g.run(`definitions(units[0])[${i}].active`))g.run(`castHeroSkill(units[0],definitions(units[0])[${i}],10,mobs[0]);tickSkillZones(1);`);assert.equal(g.run('mobs.every(m=>Number.isFinite(m.hp)&&Number.isFinite(m.p))'),true)}}});
test('even final attacks need range and do not hit distant enemies',()=>{const g=game();g.run('units=[{type:8,lv:5,slot:0}];mobs=[{...slot(0),hp:1e6,max:1e6,p:0},{x:9999,y:9999,hp:1e6,max:1e6,p:0}];castHeroSkill(units[0],definitions(units[0])[4],1,mobs[0])');assert.ok(g.run('mobs[0].hp')<1e6);assert.equal(g.run('mobs[1].hp'),1e6);g.run('castHeroSkill(units[0],definitions(units[0])[4],1,mobs[1])');assert.equal(g.run('mobs[1].hp'),1e6)});
test('chain jumps only to nearby targets and adds stun and damage over time',()=>{const g=game();g.run('units=[{type:9,lv:2,slot:0}];mobs=[0,30,60,500].map(x=>({...slot(0),x:slot(0).x+x,hp:1e6,max:1e6,p:0}));castHeroSkill(units[0],definitions(units[0])[1],10,mobs[0])');assert.equal(g.run('mobs.slice(0,3).every(m=>m.hp<1e6&&m.stun>0&&m.dotTime>0)'),true);assert.equal(g.run('mobs[3].hp'),1e6)});
test('water provides MP, cleanse and immunity without ally health',()=>{const g=game();g.run('heroLevels={"3:5":30};units=[{type:8,lv:1,slot:0},{type:3,lv:5,slot:1}];tickBattleStatus(0);tickHeroSkills(units[0],1)');assert.ok(g.run('units[0].mp')>1);assert.equal(g.run('"hp" in units[0]'),false);g.run('units[0].stun=2;units[0].slow=3;castHeroSkill(units[1],definitions(units[1])[5],1,null);castHeroSkill(units[1],definitions(units[1])[6],1,null)');assert.equal(g.run('units[0].stun+units[0].slow'),0);g.run('mobs=[{...slot(0),hp:1000,boss:true,attackCD:0}];tickBattleStatus(0)');assert.equal(g.run('units[0].stun'),0);assert.equal(g.run('"hp" in units[0]||"shield" in units[0]'),false)});
test('auras do not stack, require proximity and disappear after support removal',()=>{const g=game();g.run('units=[{type:8,lv:1,slot:0},{type:11,lv:5,slot:1}];tickBattleStatus(0)');const atk=g.run('skillModifiers(units[0]).attack');assert.ok(atk>0);g.run('units.push({type:11,lv:5,slot:1})');assert.equal(g.run('skillModifiers(units[0]).attack'),atk);g.run('units[1].slot=31;units[2].slot=30');assert.equal(g.run('skillModifiers(units[0]).attack'),0);g.run('units=units.slice(0,1)');assert.equal(g.run('skillModifiers(units[0]).attack'),0)});
test('skill upgrades persist independently for both final branches and respect unlocks',()=>{const storage=memoryStorage(),g=game(storage);g.run('essence=10000;heroLevels["8:5"]=10');assert.equal(g.run('levelUpSkill(8,5,5)'),true);assert.equal(g.run('levelUpSkill(8,5,6)'),false);assert.equal(g.run('skillRank({type:11,lv:5},5)'),0);const next=game(storage);assert.equal(next.run('skillRank({type:8,lv:5},5)'),2)});
test('v3 migration preserves invested value via merged levels and refunds old skill training exactly once',()=>{const g=game();const old={version:3,levels:{'8:5':10,'8:6':20,'11:2':5,'8:2':7},skills:{'8:6:0':3},essence:100};g.run(`var old=${JSON.stringify(old)};var clean=sanitizeMeta(old);`);assert.equal(g.run('clean.levels["8:5"]'),20);assert.equal(g.run('clean.levels["8:2"]'),7);assert.equal(g.run('clean.essence'),100+6*10*9+6*5*4+5*6*3*2);assert.equal(g.run('JSON.stringify(sanitizeMeta(clean))===JSON.stringify(clean)'),true)});
test('mana and cooldown gate skills; paused battles cannot consume evolution materials',()=>{const g=game();g.run('units=[{type:8,lv:1,slot:0}];mobs=[{...slot(0),hp:1e4,max:1e4,p:0}];tickHeroSkills(units[0],0)');assert.equal(g.run('mobs[0].hp'),1e4);g.run('units[0].mp=100;tickHeroSkills(units[0],0)');const hp=g.run('mobs[0].hp');assert.ok(hp<1e4);g.run('tickHeroSkills(units[0],0)');assert.equal(g.run('mobs[0].hp'),hp);g.run('started=true;paused=true;units=[0,1,2].map(slot=>({type:8,lv:1,slot}));');assert.equal(g.run('craftRecipe(0)'),false)});

test('melee placement reaches outside lanes but not from central slots',()=>{const g=game();for(const [w,h] of [[320,568],[390,844],[1440,900]]){g.run(`W=${w};H=${h};units=[{type:0,lv:5,slot:12}];mobs=[{x:geometry().left,y:slot(12).y,hp:100,p:0}]`);assert.equal(g.run('nearestTarget(units[0])===mobs[0]'),true);g.run('units[0].slot=13');assert.equal(g.run('!!nearestTarget(units[0])'),false);assert.ok(g.run('battleRange({type:10,lv:1})>battleRange(units[0])'))}});
test('stage badges fit inside every tile on phone and desktop',()=>{const g=game();for(const [w,h] of [[320,568],[360,640],[390,844],[1440,900]]){g.run(`W=${w};H=${h}`);assert.equal(g.run('{const b=badgeLayout(),t=tileBounds();b.x>=-t.hw&&b.y>=-t.hh&&b.x+b.w<=t.hw&&b.y+b.h<=t.hh}'),true)}});
test('shadow damage applies 2x boss, 3x normal and independent critical damage',()=>{const g=game();g.run('units=[{type:1,lv:1,slot:0}];Math.random=()=>.99');assert.equal(g.run('outgoingDamage(units[0],{boss:true},10)'),20);assert.equal(g.run('outgoingDamage(units[0],{boss:false},10)'),30);g.run('Math.random=()=>0');assert.equal(g.run('outgoingDamage(units[0],{boss:true},10)'),40)});
test('electric chain reaches every connected enemy but stops across a one-cell gap',()=>{const g=game();g.run('units=[{type:9,lv:2,slot:0}];mobs=Array.from({length:18},(_,i)=>({...slot(0),x:slot(0).x+i*20,hp:1e6,max:1e6,p:0}));mobs.push({...slot(0),x:9999,hp:1e6,max:1e6,p:0});castHeroSkill(units[0],definitions(units[0])[1],1,mobs[0])');assert.equal(g.run('mobs.slice(0,18).every(m=>m.hp<1e6&&m.stun>0)'),true);assert.equal(g.run('mobs[18].hp'),1e6)});
test('wind accelerates attacks and skill cooldowns with a bounded reduction',()=>{const g=game();g.run('heroLevels={"4:5":30};units=[{type:8,lv:1,slot:0},{type:4,lv:5,slot:1}];prepareSkills(units[0]);units[0].skillCD[0]=10;tickHeroSkills(units[0],1)');assert.ok(g.run('units[0].skillCD[0]')<9);assert.ok(g.run('skillModifiers(units[0]).speed')>0);assert.ok(g.run('skillModifiers(units[0]).haste')<=.45)});
test('finish report adds wave and final rewards without granting wave rewards twice',()=>{const g=game();g.run("S.wave=30;S.runEssence=87;essence=100;finish(true);document.querySelector('#claimBattleReward').onclick()");assert.equal(g.run('essence'),262);assert.equal(g.els.get('#rewardTotal').textContent,'+162');assert.match(g.els.get('#rewardBreakdown').textContent,/87.*45.*30/);g.run('finish(true)');assert.equal(g.run('essence'),262)});
test('catalog has unique names and no removed health or age labels',()=>{const g=game();assert.equal(g.run('new Set(catalogEntries().map(heroLabel)).size'),41);g.run('heroLevels=Object.fromEntries(catalogEntries().map(u=>[lvKey(u.type,u.lv),30]))');assert.equal(g.run('catalogEntries().flatMap(skillRows).some(s=>/아군.*HP|보호막|최대 체력/.test(s.description))'),false);g.run('renderRecipes();renderHeroLab()');assert.doesNotMatch(g.els.get('#recipeBook').innerHTML,/기본형|성장형|유년형|청소년형/)});
test('owned talismans modify battle damage, MP, speed, cooldown and start coins',()=>{const g=game();g.run("window.ForgeEconomy={bonus:(e,s)=>({attack:.1,mana:.2,speed:.1,haste:.1,skill:.1,startCoin:5}[s]||0)};units=[{type:8,lv:1,slot:0}]");assert.equal(g.run('combatAttack(units[0])'),g.run('battleAttack(units[0])*1.1'));assert.equal(g.run('skillModifiers(units[0]).speed'),.1);g.run('tickHeroSkills(units[0],1)');assert.ok(Math.abs(g.run('units[0].mp')-1.2)<1e-10);g.run('resetGame()');assert.equal(g.run('S.coin'),85)});
test('talisman essence bonus is granted exactly once and included in total',()=>{const g=game();g.run("window.ForgeEconomy={bonus:(e,s)=>s==='essence'?.05:0};S.wave=30;S.runEssence=87;essence=100;finish(true);document.querySelector('#claimBattleReward').onclick()");assert.equal(g.run('essence'),270);assert.equal(g.els.get('#rewardTotal').textContent,'+170');assert.match(g.els.get('#rewardBreakdown').textContent,/부적 보너스 8/);g.run('finish(true)');assert.equal(g.run('essence'),270)});

test("base mana recovers exactly one per second independent of frame size",()=>{const g=game();g.run("units=[{type:8,lv:1,slot:0}];for(let i=0;i<100;i++)tickHeroSkills(units[0],.01)");assert.ok(Math.abs(g.run("units[0].mp")-1)<1e-10)});

test('new random evolution consumes exactly three selected tier-four units and preserves investment',()=>{const g=game();g.run('window.ForgeAdventure={unlocked:t=>t===12||t===16,record:()=>{},final:()=>{}};started=true;units=[8,0,10,7].map((type,slot)=>({type,lv:4,slot,invested:10}));randomForgeSelection=units.slice(0,3);Math.random=()=>.99');assert.equal(g.run('craftRandomFinal()'),true);assert.equal(g.run('units.length'),2);assert.equal(g.run('units[0].type'),16);assert.equal(g.run('units[0].invested'),30);assert.equal(g.run('units[1].lv'),4);assert.equal(g.run('craftRandomFinal()'),false)});
test('random evolution excludes locked heroes and rejects invalid or duplicate materials',()=>{const g=game();g.run('started=true;units=[8,8,8].map((type,slot)=>({type,lv:4,slot}));randomForgeSelection=[...units]');assert.equal(g.run('craftRandomFinal()'),false);g.run('window.ForgeAdventure={unlocked:()=>true,record:()=>{},final:()=>{}};randomForgeSelection=[units[0],units[0],units[1]]');assert.equal(g.run('craftRandomFinal()'),false);g.run('randomForgeSelection=[...units];units[0].lv=3');assert.equal(g.run('craftRandomFinal()'),false);assert.equal(g.run('units.length'),3)});
test('collection search, sorting and next unlock reflect actual progression',()=>{const g=game();g.run('heroCollectionQuery="독화"');assert.equal(g.run('filterHeroCollection(catalogEntries()).length'),1);g.run('heroCollectionQuery="";heroCollectionSort="level";heroLevels["8:5"]=19');assert.equal(g.run('filterHeroCollection(catalogEntries())[0].type'),8);assert.match(g.run('heroMilestoneHTML({type:8,lv:5})'),/Lv.20/);assert.match(g.run('heroMilestoneHTML({type:8,lv:5})'),/1레벨 더/);g.run('heroCollectionQuery="존재하지않음";renderHeroLab()');assert.equal(g.els.get('#collectionCount').textContent,'검색 결과 0종')});
test('reward cards include diamond mission rewards and clear stale settlement values',()=>{const g=game();g.run('window.ForgeUX.rewards({notes:[{kind:"battle",diamonds:4},{kind:"mission",name:"보스 토벌",currency:"diamonds",amount:20}]})');assert.equal(g.els.get('#rewardDiamonds').textContent,'+24');assert.equal(g.els.get('#rewardMissionCount').textContent,'1개');g.run('window.ForgeUX.rewards({pending:true})');assert.equal(g.els.get('#rewardDiamonds').textContent,'정산 중');assert.equal(g.els.get('#rewardMissionList').innerHTML,'')});

test('easy mode lowers HP, increases start coins, and cannot switch mid battle',()=>{const g=game();g.run("setDifficulty('easy');resetGame();started=true;setDifficulty('normal');spawn()");assert.equal(g.run('selectedDifficulty'),'easy');assert.equal(g.run('S.coin'),120);assert.ok(g.run('mobs[0].hp')<70);g.run("started=false;setDifficulty('normal');resetGame();spawn()");assert.equal(g.run('S.coin'),80);assert.ok(g.run('mobs[0].hp')>80)});
test('inspecting skills neither pauses nor resumes an existing pause',()=>{const g=game();g.run("document.querySelector('#battleSkills').show=()=>{};started=true;units=[{type:8,lv:1,slot:0}];openBattleSkills(units[0])");assert.equal(g.run('paused'),false);g.run('paused=true;openBattleSkills(units[0])');assert.equal(g.run('paused'),true)});
test('guest battle rewards require a click and cannot be claimed twice',()=>{const g=game();g.run("essence=0;S.wave=5;S.runEssence=12;finish(false)");assert.equal(g.run('essence'),0);g.run("document.querySelector('#claimBattleReward').onclick()");assert.equal(g.run('essence'),19);g.run("document.querySelector('#claimBattleReward').onclick()");assert.equal(g.run('essence'),19)});
