'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),R=require('../public/mini-rules.js');
const placements=R.BASE.map((_,i)=>({t:0,kind:'place',slot:i,index:i}));
function config(kind,growth={},seed=31){return{kind,seed,growth,roster:R.roster(growth)}}
test('replays cannot inject a score or unauthorized roster',()=>{const c=config('slime'),a=R.replay(c,placements);assert.equal(a.king,false);assert(a.hp>50000);assert.equal(R.replay(c,placements.map(v=>({...v,damage:1e12}))).damage,a.damage);assert.equal(R.replay(c,[{t:0,kind:'place',slot:0,index:999}]).damage,0);assert.throws(()=>R.replay(c,[{t:60,kind:'place',slot:0,index:0}]));assert.throws(()=>R.replay(c,Array(121).fill(placements[0])))});
test('mine stages and support combinations react to permanent growth',()=>{const g={levels:{},unitStars:{'4:5':1,'3:5':1,'11:5':1}};const c=config('mine',g),r=R.replay(c,placements),s=R.replay(c,[{t:0,kind:'place',slot:0,index:6},{t:0,kind:'place',slot:1,index:7},{t:0,kind:'place',slot:2,index:8},...placements.slice(3)]);assert(s.damage>r.damage);assert(s.stage>r.stage);assert(s.stage<=7)});
test('roulette limits spins and trials may include an unowned legend',()=>{let seed=1;while(R.draw(config('luck',{},seed),0).tier!==5)seed++;const c=config('luck',{},seed),s=R.replay(c,[{t:0,kind:'spin',slot:0},{t:1,kind:'spin',slot:1},{t:8,kind:'spin',slot:1}]);assert.equal(s.spins,2);assert.equal(s.history[0].tier,5);assert.deepEqual(c.growth,{});assert.equal(R.replay(c,[]).damage,0)});
test('a month of daily free event rewards and optional sponsor bonuses reaches the armored king',()=>{const growth={levels:{},skills:{}},costs={gold:0,diamonds:0};let gold=0,dia=0,first=null;for(let day=1;day<=30;day++){const s=R.replay(config('slime',growth,day*31000),placements);if(s.king&&first===null)first=day;gold+=2*Math.min(1600,s.gold+({C:50,B:100,A:200,S:350}[R.grade(s.damage)]))+50;dia+=11;while(true){const t=R.BASE.slice().sort((a,b)=>(growth.levels[a+':4']||1)-(growth.levels[b+':4']||1))[0],k=t+':4',n=growth.levels[k]||1;if(n>=30||gold<n*12)break;gold-=n*12;costs.gold+=n*12;growth.levels[k]=n+1}while(true){const t=R.BASE.slice().sort((a,b)=>(growth.skills[a+':4:1']||1)-(growth.skills[b+':4:1']||1))[0],k=t+':4:1',n=growth.skills[k]||1;if(n>=10||dia<n*8)break;dia-=n*8;costs.diamonds+=n*8;growth.skills[k]=n+1}}assert(first>=20&&first<=30);assert(costs.gold>10000);assert(costs.diamonds<=330)});

function formation(growth={}){return{kind:'slime',seed:31,growth,roster:R.roster(growth,'slime'),formation:47}}
test('slime starts with six distinct attack legends and swaps without cloning',()=>{const c=formation(),s=R.create(c);assert.equal(s.units.length,6);assert.deepEqual(s.units.map(u=>u.type),R.BASE);assert(s.units.every(u=>u.tier===5&&!u.support));R.tick(s,[{t:0,kind:'place',slot:5,index:0}]);assert.equal(s.units[5].type,R.BASE[0]);assert.equal(s.units[0].type,R.BASE[5]);assert.equal(new Set(s.units.map(u=>u.index)).size,6);assert.equal(c.roster[0].type,R.BASE[0])});
test('every slot can hit the slime route even with minimum melee range',()=>{const c=formation();for(let slot=0;slot<6;slot++){const p=R.pos(slot);let nearest=Infinity;for(let j=0;j<1000;j++){const q=R.path(j/1000,c);nearest=Math.min(nearest,Math.hypot(p.x-q.x,p.y-q.y))}assert(nearest<18)}const s=R.replay(c,[]);for(const u of c.roster)assert(s.unitDamage[u.type+':5']>0);assert(!s.king);assert(s.damage>10000)});
test('legend formation: a month of daily free event rewards and optional sponsor bonuses reaches the armored king',()=>{const growth={levels:{},skills:{}},costs={gold:0,diamonds:0};let gold=0,dia=0,first=null;for(let day=1;day<=30;day++){const s=R.replay({...formation(growth),seed:day*31000},[]);if(s.king&&first===null)first=day;gold+=2*Math.min(1600,s.gold+({C:50,B:100,A:200,S:350}[R.grade(s.damage)]))+50;dia+=11;while(true){const t=R.BASE.slice().sort((a,b)=>(growth.levels[a+':5']||1)-(growth.levels[b+':5']||1))[0],k=t+':5',n=growth.levels[k]||1;if(n>=30||gold<n*12)break;gold-=n*12;costs.gold+=n*12;growth.levels[k]=n+1}while(true){const t=R.BASE.slice().sort((a,b)=>(growth.skills[a+':5:1']||1)-(growth.skills[b+':5:1']||1))[0],k=t+':5:1',n=growth.skills[k]||1;if(n>=10||dia<n*8)break;dia-=n*8;costs.diamonds+=n*8;growth.skills[k]=n+1}}assert(first>=20&&first<=30);assert(costs.gold>10000);assert(costs.diamonds<=330)});
