const {test}=require('node:test'),assert=require('node:assert/strict');const T=require('../public/talismans.js');
test('31 unique talismans, all four grades and correct star thresholds',()=>{assert.equal(new Set(T.catalog.map(t=>t.id)).size,31);assert.deepEqual([...new Set(T.catalog.map(t=>t.grade))].sort(),[0,1,2,3]);assert.deepEqual([0,1,2,3,6,7,14,15,30,31,999].map(T.stars),[0,1,2,3,6,7,14,15,20,20,20]);assert.equal(T.factor(31),2.9000000000000004)});
test('next-draw probabilities are normalized and obey all pity guarantees',()=>{for(const pity of [[0,0,0],[9,0,0],[0,49,0],[9,49,99]]){const odds=T.odds(pity);assert.ok(Math.abs(odds.reduce((s,v)=>s+v.chance,0)-1)<1e-12);const min=pity[2]>=99?3:pity[1]>=49?2:pity[0]>=9?1:0;assert.ok(odds.filter(o=>T.catalog.find(t=>t.id===o.id).grade<min).every(o=>o.chance===0))}});
test('ownership gives one effect, duplicates strengthen it and element filters remain isolated',()=>{assert.equal(T.totals({stone:1},'earth').attack,.04);assert.ok(Math.abs(T.totals({stone:2},'earth').attack-.044)<1e-12);assert.ok(Math.abs(T.totals({stone:3},'earth').attack-.048)<1e-12);assert.equal(T.totals({stone:31},'fire').attack,0);assert.ok(Math.abs(T.totals({warrior:31},'fire').attack-.058)<1e-12);assert.equal(T.totals({},'wind').haste,0)});
test('max collection remains inside every published cap',()=>{const owned=Object.fromEntries(T.catalog.map(t=>[t.id,1000000]));for(const e of Object.keys(T.elements))for(const [k,v]of Object.entries(T.totals(owned,e)))assert.ok(v<=T.caps[k])});
const A=require('../lib/account.cjs'),handler=require('../api/talismans.js');
test('economy API denies unauthenticated requests and paid/ad reward spoofing',async()=>{const old=A.identity;const res=()=>({setHeader(){},status(n){this.statusCode=n;return this},json(v){this.body=v}});const req=body=>({method:'POST',headers:{origin:process.env.APP_ORIGIN||'https://randomfortune-game.vercel.app','x-forge-request':'1','content-type':'application/json'},body});try{A.identity=async()=>null;let r=res();await handler(req({action:'load'}),r);assert.equal(r.statusCode,401);A.identity=async()=>({user:{id:'user'},token:'x'});for(const action of ['pay','adReward','grant','save']){r=res();await handler(req({owner:'user',action}),r);assert.equal(r.statusCode,400)}r=res();await handler(req({owner:'other',action:'load'}),r);assert.equal(r.statusCode,409)}finally{A.identity=old}});

test('level 20 is capped and zero ownership never gives a level bonus',()=>{assert.equal(T.levelFactor(20),1.95);assert.equal(T.levelFactor(999),1.95);assert.equal(T.upgradeCost(0,1),5);assert.equal(T.upgradeCost(3,19),380);assert.equal(T.upgradeCost(2,20),0);assert.equal(T.totals({},'fire',{flame:20}).skill,0);assert.ok(T.totals({flame:1},'fire',{flame:20}).skill>T.totals({flame:1},'fire').skill)});
