const {PGlite}=require('@electric-sql/pglite'),fs=require('fs'),assert=require('node:assert/strict'),{randomUUID}=require('crypto');
(async()=>{const db=new PGlite();await db.exec(`create schema auth;create schema private;create role anon;create role authenticated;create table auth.users(id uuid primary key);create table public.player_progress(user_id uuid primary key,data jsonb);create function auth.uid() returns uuid language sql as $$select nullif(current_setting('request.jwt.claim.sub',true),'')::uuid$$;`);for(const f of ['20260928000000_talisman_economy.sql','20260928000853_adventure_v20.sql','20260928184547_beginner_rewards_v22.sql'])await db.exec(fs.readFileSync('supabase/migrations/'+f,'utf8'));const user=randomUUID();await db.query('insert into auth.users values($1)',[user]);await db.query('insert into public.player_progress values($1,$2)',[user,{version:4,essence:1000,levels:{'8:5':10},skills:{'8:5:0':2}}]);await db.query("select set_config('request.jwt.claim.sub',$1,false)",[user]);const call=async(action,payload={},id=randomUUID())=>(await db.query('select public.forge_adventure($1,$2,$3) v',[action,id,payload])).rows[0].v;

let r=await call('load');assert.equal(r.attendanceCount,0);assert.equal(r.gold,1000);
r=await call('attend');assert.equal(r.gold,1030);assert.equal((await call('attend')).gold,1030);
await db.exec("update private.adventure_wallets set stats='{\"kills\":1000}',diamonds=10000;update private.talisman_wallets set owned='{\"flame\":1}'");
r=await call('load');assert.equal(r.gold,1030);const mid=randomUUID();r=await call('claim_mission',{key:'kills:0'},mid);assert.equal(r.gold,1330);assert.deepEqual(await call('claim_mission',{key:'kills:0'},mid),r);assert.equal((await call('claim_mission',{key:'kills:0'})).error,'MISSION');
const upid=randomUUID();r=await call('talisman_level',{id:'flame'},upid);assert.equal(r.talismanLevels.flame,2);assert.equal(r.diamonds,9990);assert.deepEqual(await call('talisman_level',{id:'flame'},upid),r);await assert.rejects(call('talisman_level',{id:'missing'}));
for(let i=2;i<20;i++)r=await call('talisman_level',{id:'flame'});assert.equal(r.talismanLevels.flame,20);assert.equal((await call('talisman_level',{id:'flame'})).error,'FUNDS');
for(const difficulty of ['easy','normal']){r=await call('run_start',{difficulty});const run=r.activeRun,beforeGold=r.gold,beforeDiamonds=r.diamonds;await db.exec("update private.adventure_wallets set run_started=now()-interval '100 seconds'");const rid=randomUUID();r=await call('run_end',{run,wave:5,elapsed:90,won:false,stats:{bosses:1},finals:[]},rid);assert.equal(r.gold,beforeGold);assert.equal(r.diamonds,beforeDiamonds);assert.equal(r.pendingBattle.gold,difficulty==='easy'?13:19);assert.equal(r.pendingBattle.diamonds,difficulty==='easy'?1:2);assert.equal((await call('run_start',{difficulty})).error,'PENDING_REWARD');const cid=randomUUID();r=await call('claim_battle',{},cid);assert.equal(r.gold,beforeGold+(difficulty==='easy'?13:19));assert.deepEqual(await call('claim_battle',{},cid),r);assert.equal((await call('claim_battle')).error,'OWNED');}
await assert.rejects(call('run_start',{difficulty:'cheat'}));
await db.exec("select set_config('request.jwt.claim.sub','',false)");await assert.rejects(call('talisman_level',{id:'flame'}));
await db.close();console.log('V22 SQL PASS: explicit claims, replay safety, level cap, diamond costs, ownership, difficulty-bound rewards');
})().catch(e=>{console.error(e);process.exit(1)});
