const A=require('../lib/account.cjs');
module.exports=async(req,res)=>{try{A.guard(req,res);const b=A.input(req),action=b.action;
 if(action==='status'){if(!A.config())return res.status(200).json({configured:false,user:null});const auth=await A.identity(req,res);return res.status(200).json({configured:true,user:auth?A.publicUser(auth.user):null})}
 if(action==='delete'){const auth=await A.identity(req,res);if(!auth)throw new A.Fault(401,'SIGN_IN','계정 삭제를 위해 다시 로그인해 주세요.');await A.upstream('/rest/v1/rpc/delete_forge_account',{method:'POST',token:auth.token,body:{}});A.clearSession(res);return res.status(200).json({ok:true})}
 if(action==='logout'){const auth=await A.identity(req,res);if(auth)await A.upstream('/auth/v1/logout?scope=local',{method:'POST',token:auth.token});A.clearSession(res);return res.status(200).json({ok:true})}
 if(action==='signin'||action==='signup'){const body={email:A.email(b.email),password:action==='signup'?A.newPassword(b.password):A.password(b.password)};if(action==='signup')body.data={nickname:A.nickname(b.nickname)};const data=await A.upstream(action==='signup'?'/auth/v1/signup':'/auth/v1/token?grant_type=password',{method:'POST',body});if(data.access_token){A.setSession(res,data);return res.status(200).json({user:A.publicUser(data.user)})}return res.status(200).json({confirmationRequired:true})}
 if(action==='resend'||action==='recover'){const mail=A.email(b.email);await A.upstream(action==='recover'?'/auth/v1/recover':'/auth/v1/resend',{method:'POST',body:action==='recover'?{email:mail}:{email:mail,type:'signup'}});return res.status(200).json({ok:true,message:'인증 가능한 주소라면 이메일이 발송됩니다.'})}
 if(action==='verify'||action==='reset'){if(typeof b.code!=='string'||!/^\d{6,10}$/.test(b.code))throw new A.Fault(400,'CODE','이메일로 받은 인증번호를 입력해 주세요.');const pw=action==='reset'?A.newPassword(b.password):null;const data=await A.upstream('/auth/v1/verify',{method:'POST',body:{email:A.email(b.email),token:b.code,type:action==='reset'?'recovery':'signup'}});if(action==='reset'){await A.upstream('/auth/v1/user',{method:'PUT',token:data.access_token,body:{password:pw}});await A.upstream('/auth/v1/logout?scope=global',{method:'POST',token:data.access_token});A.clearSession(res);return res.status(200).json({ok:true})}A.setSession(res,data);return res.status(200).json({user:A.publicUser(data.user)})}
 throw new A.Fault(400,'ACTION','지원하지 않는 요청입니다.');
}catch(e){A.fail(res,e)}};
